### ISSUE TITLE
Python is not running correctly in the sandbox.

### ISSUE THREAD

**Issue by masnn** [criyle/go-judge#1]

**Comment by criyle** [comment]
If possible, please provides the Args and Env parameters with the python scripts to help me diagnose. Thanks. (I am kind of busy right now and I would test it 2 days later. )

**Comment by masnn** [comment]
No args needed.
Python cannot init.

**Comment by criyle** [comment]
I can run python2, python3 version of a+b problem on https://goj.ac/ which uses the same technology. Have you tried add "HOME=/w" to the env parameter? if so, does it solve the problem?

**Comment by masnn** [comment]
Problem solved. Thank you.

**Comment by masnn** [comment]
Error compiling haskell:

```
ghc: can't find a package database at /usr/lib/ghc/package.conf.d
```

**Comment by criyle** [comment]
I pushed a change to add a bind mount from `/var/lib/ghc` into the container. Please have a try, thank you.

**Comment by criyle** [comment]
I planned in the next version, there will be a config file or command line arguments defining all the container mounts points to make recompile not required for changing mounts....
