### ISSUE TITLE
docker部署出错

### ISSUE THREAD

**Issue by ydyydsediz** [criyle/go-judge#104]
{"level":"info","ts":1714764180.5343466,"caller":"go-judge/main.go:58","msg":"config loaded: &{ContainerInitPath: PreFork:1 TmpFsParam:size=128m,nr_inodes=4k NetShare:false MountConf:mount.yaml SeccompConf:seccomp.yaml Parallelism:2 CgroupPrefix:gojudge ContainerCredStart:0 SrcPrefix:[] Dir: TimeLimitCheckerInterval:100ms ExtraMemoryLimit:16.0 KiB OutputLimit:256.0 MiB CopyOutLimit:256.0 MiB OpenFileLimit:256 Cpuset: EnableCPURate:false CPUCfsPeriod:100ms FileTimeout:0s HTTPAddr::5050 EnableGRPC:false GRPCAddr::5051 MonitorAddr::5052 AuthToken: GRPCMsgSize:64.0 MiB EnableDebug:false EnableMetrics:false Release:true Silent:false ForceGCTarget:20.0 MiB ForceGCInterval:5s Version:false}"}
{"level":"info","ts":1714764180.5352476,"caller":"env/env_linux.go:63","msg":"Created container mount at:Mounts: bind[/bin:bin:ro], bind[/lib:lib:ro], bind[/lib64:lib64:ro], bind[/usr:usr:ro], bind[/etc/ld.so.cache:etc/ld.so.cache:ro], bind[/etc/alternatives:etc/alternatives:ro], bind[/dev/null:dev/null:rw], bind[/dev/urandom:dev/urandom:rw], bind[/dev/random:dev/random:rw], bind[/dev/zero:dev/zero:rw], bind[/dev/full:dev/full:rw], tmpfs[w], tmpfs[tmp], tmpfs[dev/shm], bind[/sys:sys:rw], proc[ro]"}
{"level":"info","ts":1714764180.5354295,"caller":"env/env_linux.go:106","msg":"Initialize container with command: ip link set dev lo up"}
{"level":"info","ts":1714764180.5354571,"caller":"env/env_linux.go:109","msg":"Creating container builder: hostName=go-judge, domainName=go-judge, workDir=/w"}
{"level":"info","ts":1714764180.5675755,"caller":"env/env_linux.go:223","msg":"Creating nesting api cgroup v1(gojudge)[cpu, cpuset, cpuacct, memory, pids]"}
{"level":"info","ts":1714764180.569216,"caller":"env/env_linux.go:234","msg":"Creating containers cgroup"}
{"level":"info","ts":1714764180.573331,"caller":"go-judge/main.go:275","msg":"create 1 prefork containers"}
container_exit: serve: failed to execute cmd exec: "ip": executable file not found in $PATH
2024/05/03 19:23:00 prefork environment failed  conf: recvAck RecvMsg: read unixpacket @->@: EOF

以下是版本：
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

内核：
Linux version 5.4.0-174-generic (buildd@bos03-amd64-026) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)) #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024

**Comment by criyle** [comment]
好像是上个版本的配置文件改动造成的，可以暂时 `docker exec -it 容器名 /bin/bash` 进入容器，然后改动 `/opt/mount.yaml` 配置文件删除最后一行。

**Comment by ydyydsediz** [comment]
> 好像是上个版本的配置文件改动造成的，可以暂时 `docker exec -it 容器名 /bin/bash` 进入容器，然后改动 `/opt/mount.yaml` 配置文件删除最后一行。

可是部署都没有成功，都看不到容器，没办法修改，请指点一下

**Comment by criyle** [comment]
可以去使用刚发布的最新版镜像。如果 latest 没有更新，可以试试 `v1.8.4` tag，如果不存在，可以使用上一个版本 `v1.8.2`

**Comment by ydyydsediz** [comment]
> 可以去使用刚发布的最新版镜像。如果 latest 没有更新，可以试试 `v1.8.4` tag，如果不存在，可以使用上一个版本 `v1.8.2`

成功了成功了，感谢感谢
