### ISSUE TITLE
程序是否有处理并发错误

### ISSUE THREAD

**Issue by euphonium1998** [criyle/go-judge#11]
![image](https://user-images.githubusercontent.com/54737731/114864318-6d50fc00-9e23-11eb-8b45-02ead22036d3.png)
你好作者，我想问一下如果多人同时在沙箱中编译同名称的c++代码，是否会存在并发错误

**Comment by euphonium1998** [comment]
就是说要避免这种错误，需要我自己从编码层面（比如传入文件命名不重复）考虑而沙箱无法回避这类错误？

**Comment by euphonium1998** [comment]
你好作者，我使用之后发送你通过fileId确定文件而不是传入的文件名确认文件。所以应该不会有并发错误。
但现在有个新的问题。因为传入的文件默认是没有删除的，所以是否在使用沙箱判题之后最好调用delete方法清楚使用的文件？

**Comment by criyle** [comment]
你好，并行执行的请求是在不同沙箱实例中执行的，同时返回的文件ID是随机生成同时保证不冲突的，理论上不会产生并发冲突。文件需要在使用后显性删除，如果不掉用delete方法，会使文件一直占有内存。

**Comment by undefined-moe** [comment]
feat: --file-timeout=30min 即自动删除30min内未使用的文件

**Comment by euphonium1998** [comment]
thx
