### ISSUE TITLE
openjdk21执行Java报错Exception in thread "main" java.lang.InternalError: Error loading java.security file

### ISSUE THREAD

**Issue by 404-error-404** [criyle/go-judge#119]
环境：WSL (Ubuntu24.04)
版本：go-judge 1.8.5，通过deb包安装
jdk：openjdk-21-jdk，通过apt安装

报错与这个这个issues相同：https://github.com/criyle/go-judge/issues/75
issue里边的解决方案是进入容器，添加对应的配置

我的操作：
1. 去action下载最新的go-judge-shell：https://github.com/criyle/go-judge/actions/runs/10913269797
2. 运行go-judge
3. 运行go-judge-shell，请问解决方案里边的`进入容器`是这一步吗？
4. 容器中没有/opt目录，全局查找moumt.yaml文件也没找到，到这卡住了

**Comment by criyle** [comment]
deb包可能并没有打包 `mount.yaml` 文件，可以在仓库中下载

**Comment by 404-error-404** [comment]
感谢，解决了，go-judge会默认在执行命令的文件夹找mount.yaml文件，使用命令启动的时候指定文件即可
我的解决流程：

1. 下载mount.yaml文件到服务器(任意目录)，在该文件所在目录执行go-judge命令，成功执行Java
2. go-judge -h命令查看帮助，有一条`-mount-conf`命令，执行`go-judge -mount-conf <mount文件路径>`(对所在文件夹无要求)，成功执行Java

over，感谢大佬！
