### ISSUE TITLE
可不可以添加一个 Status.UnmarshalJSON 方法？

### ISSUE THREAD

**Issue by yzy-1** [criyle/go-judge#12]
您好作者，可不可以在 `cmd/executorserver/model/model.go` 中添加一个 Status.UnmarshalJSON 方法，来把字符串再转回枚举？

我在用 go 对 executorserver 提供的 REST API 包装时遇到的问题：没有办法将 API 返回的 json 数据转回 Result。具体原因是无法将 Marshal 出来的 string 重新变成枚举。

---

你可能会问的问题：

- **Q:** 为什么不重新写一个 "MyResult" 结构体，然后写个函数把 API 返回的 json 数据转成 "MyResult"？
- **A:** 万一那天这个项目更新，把 `model.Result` 结构体重写了，我的包装不就出 bug 了吗？我想使我的包装一直兼容这个项目的最新 Release。

**Comment by undefined-moe** [comment]
似乎使用if就可以（

**Comment by yzy-1** [comment]
你的意思是：

1. 将 json 数据中的 result 字段手动传成枚举，覆盖掉源数据；
2. 将改好的数据通过 Unmarshal 回 `model.Result`。

是这样实现吗？

如果是的话，那这个实现不能保证兼容性，如果这个项目增加了一种新 result 枚举项，包装层代码还是要改的。

**Comment by undefined-moe** [comment]
result已经定型了基本不会修改

**Comment by yzy-1** [comment]
那就行，可是我感觉这种只能从 stuct 转 json，不能 json 转 struct 的「单向」设计不是很好，要不我自己开个 pr 加个 UnmarshalJSON？

**Comment by undefined-moe** [comment]
这种通过http对接的服务你在这里写转换意义不大吧（
别人换一种语言不还是得自己实现

**Comment by criyle** [comment]
感谢使用。目前该项目的接口已经进入稳定状态，不太会有修改了。具体枚举类型的定义可以参照 [状态](https://github.com/criyle/go-judge/blob/master/README.cn.md#run-%E6%8E%A5%E5%8F%A3%E8%BF%94%E5%9B%9E%E7%8A%B6%E6%80%81)。暂时该项目没有提供 REST API 接口的客户端包，或许可以尝试用 gRPC 的方式（定义在 /pb 下）。
