### ISSUE TITLE
go error obtaing buildID for go tool compile: fork/exec /usr/lib/go-1.22/pkg/tool/linux_amd64/compile: resource temporarily unavailable

### ISSUE THREAD

**Issue by 404-error-404** [criyle/go-judge#120]
我做的：
1. 开发模式部署Hydro
2. apt安装go
3. 通过deb包的形式安装go－judge，启动参数指定mount.yaml文件（仅修改jdk配置）
4. 前端提交go代码，报错`go error obtaing buildID for go tool compile: fork/exec /usr/lib/go-1.22/pkg/tool/linux_amd64/compile: resource temporarily unavailable`

我尝试的：
1. 验证go环境是否正常，命令行编译go的helloworld代码，能够正常编译，编译后能够正常执行
2. 查阅go－judge文档，发现有这两个设置
   -force-gc-interval
   -force-gc-target
  增加-force-gc-target到1000m，重启go－judge，不行
3. 网上查资料，配置GOROOT和GOPATH，因为不是源码安装的，尝试了配置GOROOT为`/usr/share/go-1.22/` `/usr/lib/go/` `/usr/lib/go-1.22/`，在终端配置上述环境变量，并配置GOPATH为一个新的空目录，然后在当前终端启动go－judge，均失败

没办法了，只能来求助大佬，感谢！

**Comment by criyle** [comment]
在 hydrooj 控制面板增加评测线程数限制限制，或者尝试在控制面板环境变量中添加 GOMAXPROCS=1 限制

**Comment by 404-error-404** [comment]
感谢！`在控制面板环境变量中添加 GOMAXPROCS=1 限制`，这个能解决我的问题
![image](https://github.com/user-attachments/assets/3760458c-c5ff-4da2-a863-fc5731ebee20)


然后想问下`控制面板增加评测线程数限制限制`这个能说一下配置哪些项吗？我试着改大`singleTaskParallelism` `parallelism` `processLimit` `stdio_size`都不行

**Comment by criyle** [comment]
processLimit 因为默认 go 会使用和 CPU 核数相同甚至更多的线程，所以在很多线程的 CPU 上，容易超过限制。使用环境变量会更好。

**Comment by 404-error-404** [comment]
感谢解答，默认的是32过不了，改成64没过，改成100可以了
