### ISSUE TITLE
optional copyOut

### ISSUE THREAD

**Issue by undefined-moe** [criyle/go-judge#14]
当要求选手使用文件IO，但选手未创建文件时会返回File Error，且message无法判断是选手文件丢失还是其他文件丢失（同时返回错误文件名）？

希望允许optional选项，在文件不存在时返回空串或采用其他可辨识方案。

https://github.com/hydro-dev/Hydro/issues/153

**Comment by criyle** [comment]
期望 API 变更：

- 加入 `copyOutOptional: string[]`，效果等同于 `copyOut` 
- 如果目标文件不存在， `Result.status` 将不会设为 `FileError` 同时 `Result.files` 将不会存在该文件 key

如果有其它的提案，欢迎补充

**Comment by undefined-moe** [comment]
直接copyOut:['filename?']是不是可以简化接口

**Comment by criyle** [comment]
`?` 是合法的路径字符，这种实现方式会带来歧义

**Comment by undefined-moe** [comment]
我不认为通配符指代会在copyOut中用到（？

**Comment by criyle** [comment]
那期望 API 变更：

- 允许在 `copyOut` 和 `copyOutCached` 路径最后加入字符 `?` ， 该字符会在访问文件是去除
- 如果目标文件不存在，`Result.status` 将不会设为 `FileError` 同时 `Result.files` 将不会存在该文件 key

如果有其它的提案，欢迎补充

**Comment by criyle** [comment]
根据这个想法实现了一个版本，调用此 api 之前可能需要通过 `/version` 接口确认支持情况 （将会有一个字段 `copyOutOptional: true` ）
