### ISSUE TITLE
如何扩展多语言和sql呀？

### ISSUE THREAD

**Issue by kaiwenli** [criyle/go-judge#17]
如何扩展多语言和sql呀？

**Comment by criyle** [comment]
本项目仅为通用沙箱实现。如果需要使用本项目实现oj，请参照 https://goj.ac 测试站。https://github.com/criyle/go-judger-demo

**Comment by kaiwenli** [comment]
谢谢! 你的项目写的太棒了，我到好多oj项目中都使用到了你的sandbox。

我已经在测试和学习了。不过想增加sql上的实现。

我先下载编译看一下哈，谢谢！
