### ISSUE TITLE
feat request: kill task

### ISSUE THREAD

**Issue by undefined-moe** [criyle/go-judge#24]
on a websocket connection, run operation returns a taskId, and allow kill the specific task with id immediately (even when time limit isn't reached)

**Comment by criyle** [comment]
For clarification, the run operation does not return a `taskId`, but client need to provide a `requestId` to distinguish different requests. The following proposal is assuming that: for each web socket connection, the `requestId` is provided by client for every request and the provided `requestId` are different.

The proposal is to add a new type of web socket request

```typescript
// exsiting
interface Request {
    requestId: string;
    cmd: Cmd[];
    pipeMapping: PipeMap[];
};

// new
interface CancelRequest {
    cancelRequestId: string;
};

type WSRequest = Request | CancelRequest;
```

When receiving `RunRequest`, the running context will be saved to connection local dictionary and removed upon complete.

When receiving `CancelRequest`, the given `cancelRequestId` will be used to find the correspond context and cancel it if presented. Canceling a running task will result in `SIGKILL` to the running process and the correspond result would be replied afterwards with `Signalled` status.

To enforce the assumption of no duplicated / empty `requestId`, an `Internal Error` would be replied if attempting to request with the same `requestId`.

If you have any other suggestion, please comment below. I'll start the implementation as proposed tomorrow.

**Comment by undefined-moe** [comment]
it's seems great. maybe auto kill running tasks when client disconnnect?
