### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by kouxin** [criyle/go-judge#25]
centos7  kernel：3.10.0-1160.11.1.el7.x86_64
./executorserver-amd64
prefork environment failed container: failed to start container fork/exec /proc/self/exe: invalid argument

**Comment by undefined-moe** [comment]
看起来是内核版本太低了。

**Comment by kouxin** [comment]
> 看起来是内核版本太低了。
是的，我升级了内核，可以正常启动了，不清楚这个最低内核应该是多少，反正这个内核不行
