### ISSUE TITLE
java编译后运行出现ClassNotFound的问题

### ISSUE THREAD

**Issue by HimitZH** [criyle/go-judge#26]
如果代码中有使用了多个类，例如内部类，new一个类，那么编译后会形成多个class文件，例如Main.class, Main$sc.class....，这样的多个文件， copyOutCached很难明确指明每个class的名称，编译后只能返回Main.class的FileId，再次发送Main.class的FileId进行java Main运行的请求，就会出现ClassNotFound的报错，可能新的请求已经不在原来编译的文件夹进行运行了，所以代码中那些类的class文件已经丢失或不在新的请求创建的文件夹里面，那该如何解决这个问题呢？

**Comment by HimitZH** [comment]
下面是代码例子
```java
import java.io.*;
import java.lang.*;

public class Main {
    static BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    static StreamTokenizer pq = new StreamTokenizer(br);

    public static boolean IsPrimeNumber(int a) {
        if ((a & 1) == 0) {
            return false;
        }
        for (int k = 3; k <= Math.sqrt(a); k += 2) {
            if (a % k == 0) {
                return false;
            }
        }
        return true;
    }

    static class sc {
        static int nextInt() throws IOException {
            pq.nextToken();
            return (int) pq.nval;
        }

        static double nextDouble() throws IOException {
            pq.nextToken();
            return (double) pq.nval;
        }

        static long nextLong() throws IOException {
            pq.nextToken();
            return (long) pq.nval;
        }

        static int[] nextIntarr(int a[]) throws IOException {
            for (int i = 0; i < a.length; i++) {
                a[i] = sc.nextInt();
            }
            return a;
        }

        static long[] nextLongarr(long a[]) throws IOException {
            for (int i = 0; i < a.length; i++) {
                a[i] = sc.nextLong();
            }
            return a;
        }
    }

    static class Out {
        static void outIntarr(int a[]) throws IOException {
            for (int i = 0; i < a.length; i++) {
                System.out.print(a[i] + " ");
            }
        }

        static void outLongarr(long a[]) throws IOException {
            for (int i = 0; i < a.length; i++) {
                System.out.print(a[i] + " ");
            }
            System.out.println();
        }
    }

    public static void main(String[] args) throws NumberFormatException, IOException {
        int a =sc.nextInt();
        int b =sc.nextInt();
        System.out.println(a+b);
    }
}
```

**Comment by criyle** [comment]
可以尝试把生成的 class 文件打包成一个 jar 文件然后 copyOut ，比方说编译的时候

`/usr/bin/bash -c "javac Main.java && jar cvf Main.jar *.class"`

copyOut `Main.jar`

运行

copyIn `Main.jar`

`/usr/bin/java -cp Main.jar Main`

**Comment by HimitZH** [comment]
> 
按照作者你这样配置，但是出现了 FileError:[{Name:Main.jar Type:CopyOutOpen Message:open Main.jar: no such file or directory}]}] Error:<nil>
Main.jar是想返回拿到fileId 所以使用了 "copyOutCached": ["Main.jar"]

**Comment by HimitZH** [comment]
> 可以尝试把生成的 class 文件打包成一个 jar 文件然后 copyOut ，比方说编译的时候
> 
> `/usr/bin/bash -c "javac Main.java && jar cvf Main.jar *.class"`
> 
> copyOut `Main.jar`
> 
> 运行
> 
> copyIn `Main.jar`
> 
> `/usr/bin/java -cp Main.jar Main`

按照作者你这样配置，但是出现了 FileError:[{Name:Main.jar Type:CopyOutOpen Message:open Main.jar: no such file or directory}]}] Error:
Main.jar是想返回拿到fileId 所以使用了 "copyOutCached": ["Main.jar"]

**Comment by HimitZH** [comment]
完整的日志如下：

est_executor/cmd_handler.go:67	request: &{RequestID: Cmd:[{Args:[/usr/bin/bash -c "javac -encoding utf8 Main.java && jar -cvf Main.jar *.class"] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 HOME=/w] Files:[memory:(len:0) collector:(name:stdout,max:16777216,pipe:false) collector:(name:stderr,max:16777216,pipe:false)] TTY:false CPULimit:5s ClockLimit:10s MemoryLimit:512.0 MiB StackLimit:128.0 MiB OutputLimit:0 B ProcLimit:128 OpenFileLimit:0 CPURateLimit:0 CPUSetLimit: StrictMemoryLimit:false CopyIn:map[Main.java:memory:(len:746)] CopyOut:[{Name:stdout Optional:false} {Name:stderr Optional:false}] CopyOutCached:[{Name:Main.jar Optional:false}] CopyOutMax:0 CopyOutDir:}] PipeMapping:[]}



{RequestID: Results:[{Status:Internal Error ExitStatus:0 Error:execve: start: execve: no such file or directory Time:361.099µs RunTime:0s Memory:128.0 KiB Files:map[stderr:(path:/dev/shm/executorserver1022144392/TQAJMK3WZUZHHYUJ) stdout:(path:/dev/shm/executorserver1022144392/4HHG2E7GW77NEJI4)] FileIDs:map[] FileError:[{Name:Main.jar Type:CopyOutOpen Message:open Main.jar: no such file or directory}]}] Error:<nil>}

**Comment by criyle** [comment]
`no such file or directory` 看起来是 `/usr/bin/bash` 文件并不存在，可以试试改成 `/bin/bash`，也可以通过 `which bash` 查看路径

**Comment by HimitZH** [comment]
> `no such file or directory` 看起来是 `/usr/bin/bash` 文件并不存在，可以试试改成 `/bin/bash`，也可以通过 `which bash` 查看路径

我尝试过在运行sandbox的本机环境里使用 bash -c "javac -encoding utf8 Main.java && jar -cvf Main.jar *.class" 是可以正常编译生成jar包的，但是发送http请求给sandbox就也是出现 open Main.jar: no such file or directory的错误，还是说sandbox里面的命令要绝对路径 例如你说的 /bin/bash

**Comment by criyle** [comment]
sandbox 目前 arg0 参数需要绝对路径，并没有实现使用 PATH 来寻找可执行文件

**Comment by HimitZH** [comment]
> /usr/bin/java -cp Main.jar Main

好的，等会我试试，感谢作者的耐心解答，如还有问题，我会在该issue继续询问。

**Comment by HimitZH** [comment]
> `no such file or directory` 看起来是 `/usr/bin/bash` 文件并不存在，可以试试改成 `/bin/bash`，也可以通过 `which bash` 查看路径

使用 /bin/bash -c "javac Main.java && jar cvf Main.jar *.class"

出现下面的报错

Main.java: -c: line 0: unexpected EOF while looking for matching `”
Main.java: -c: line 1: syntax error: unexpected end of file

**Comment by HimitZH** [comment]
以下是在与SandBox同环境进行的命令 可以成功打包成jar
root@bfc71a42cd98:/judge/server# /bin/bash -c 'javac Main.java && jar cvf Main.jar *.class'
added manifest
adding: Main$Out.class(in = 955) (out= 550)(deflated 42%)
adding: Main$sc.class(in = 911) (out= 526)(deflated 42%)
adding: Main.class(in = 1174) (out= 721)(deflated 38%)

但是发送给SandBox就不行了

2021-11-24T13:05:11.570+0800	DEBUG	rest_executor/cmd_handler.go:67	request: &{RequestID: Cmd:[{Args:[/bin/bash -c 'javac Main.java && jar cvf Main.jar *.class'] Env:[HOME=/w] Files:[memory:(len:0) collector:(name:stdout,max:16777216,pipe:false) collector:(name:stderr,max:16777216,pipe:false)] TTY:false CPULimit:10s ClockLimit:20s MemoryLimit:512.0 MiB StackLimit:128.0 MiB OutputLimit:0 B ProcLimit:128 OpenFileLimit:0 CPURateLimit:0 CPUSetLimit: StrictMemoryLimit:false CopyIn:map[Main.java:memory:(len:746)] CopyOut:[{Name:stdout Optional:false} {Name:stderr Optional:false}] CopyOutCached:[{Name:Main.jar Optional:false}] CopyOutMax:0 CopyOutDir:}] PipeMapping:[]}

报错提示如下：
Main.java: -c: line 0: unexpected EOF while looking for matching `''
Main.java: -c: line 1: syntax error: unexpected end of file

**Comment by criyle** [comment]
应该是 Args 的格式不太对，试试 `args:["/bin/bash", "-c", "javac Main.java && jar cvf Main.jar *.class"]`

**Comment by HimitZH** [comment]
> 应该是 Args 的格式不太对，试试 `args:["/bin/bash", "-c", "javac Main.java && jar cvf Main.jar *.class"]`

谢谢，确实是这个问题，已经能成功编译运行了，谢谢作者！这个issue可以关了
