### ISSUE TITLE
[Help] Compile and execute submited solution on Windows 10

### ISSUE THREAD

**Issue by riverstore** [criyle/go-judge#27]
Hi, I'm trying to compile and execute submited solution on Windows 10. I can compile the solution by sending this to /run

```
{
  "cmd": [
    {
      "args": [
        "g:\\cygwin64\\bin\\g++.exe",
        "-Wall",
        "-std=c++98",
        "-o",
        "code.exe",
        "foo.cc",
        "-lm"
      ],
      "env": [
        "PATH=d:\\\\Download\\\\ThemisSFX_4\\\\FPC\\\\bin\\\\i386-win32;g:\\\\hydro;g:\\\\cygwin64\\\\bin;\r",
        "HOME=g:\\\\hydro\r",
        ""
      ],
      "files": [
        {
          "content": ""
        },
        {
          "name": "stdout",
          "max": 33554432
        },
        {
          "name": "stderr",
          "max": 33554432
        }
      ],
      "cpuLimit": 16000000000,
      "realCpuLimit": 48000000000,
      "memoryLimit": 536870912,
      "strictMemoryLimit": false,
      "procLimit": 32,
      "copyIn": {
        "foo.cc": {
          "content": "#include <bits/stdc++.h>\r\nusing namespace std;\r\nint a,b;\r\nint main() {\r\n    freopen(\"a+b.in\", \"r\", stdin);\r\n    freopen(\"a+b.out\", \"w\", stdout);\r\n     \r\n    ios::sync_with_stdio(0);\r\n    cin.tie(0);\r\n    cout.tie(0);\r\n    cin >> a;\r\n    cin >> b;\r\n    cout << (a+b);\r\n    return 0;\r\n}"
        }
      },
      "copyOut": [],
      "copyOutCached": [
        "code.exe"
      ]
    }
  ]
}
```
On Linux, I can pass `/w/code` to `args` field to execute the compiled solution. But on Windows I don't know how. I tried setting the output path to something like `g:\run\code.exe` for `code.exe` but i get error like below (I run `executorserver-amd64.exe` as adminstrator and also change permission to `Eveyrone` for `g:\run` with `Full control` ) 

```
[{'status':'Nonzero Exit Status','exitStatus':1,'time':1046875000,'memory':75116544,'runTime':0,'files':{'stderr':'/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: cannot open output file g:\\code.exe: Permission denied\ncollect2: error: ld returned 1 exit status\n','stdout':''},'fileError':[{'name':'code.exe','type':'CopyOutOpen','message':'open C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\es4154887469/code.exe: The system cannot find the file specified.'}]}]
```
Please help me. 
Thank a lot.
Regard.

**Comment by criyle** [comment]
Please use the current folder as output path and download the file from the copyOutCached using API. Since windows does not provide SDK for its container implementation, the current sandbox implementation is similar to Chrome browser where it lowers the mandaroty access control level to restrict the access to the file system (thus, permission denied). However, the program is still able to list files and access network within the sandbox, so Windows is not designed to be used in production environment and Linux (or WSL2) is recommended.

**Comment by riverstore** [comment]
Thank a lot for your help.

It work for me now.

Thanks again and best regard.
