### ISSUE TITLE
测试样例能不能详细一点

### ISSUE THREAD

**Issue by fakerlove1** [criyle/go-judge#28]
我想问一下，这个样例我不是很懂耶。
我觉得应该是输入，代码，输出。三个命令

**Comment by criyle** [comment]
具体是指哪一个例子？

注意本项目仅为沙箱实现，只提供程序运行时环境，并不提供编译、文件输入输出和对比功能。如果想使用本项目实现 oj ，可以参照这个 demo ：https://github.com/criyle/go-judger-demo
