### ISSUE TITLE
关于文件上传api /file POST 上传失败

### ISSUE THREAD

**Issue by zzzyc** [criyle/go-judge#30]
请问这个上传文件的api /file POST 在上传一个文件时报错

ERROR   zap@v0.0.2/zap.go:62    http: no such file                                                                                           github.com/gin-contrib/zap.GinzapWithConfig.func1                                                                                                                                    /home/runner/go/pkg/mod/github.com/gin-contrib/zap@v0.0.2/zap.go:62                                                                                                  github.com/gin-gonic/gin.(*Context).Next                                                                                                                                             /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168                                                                                               github.com/gin-gonic/gin.(*Engine).handleHTTPRequest                                                                                                                                 /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555                                                                                                   github.com/gin-gonic/gin.(*Engine).ServeHTTP                                                                                                                                         /home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511                                                                                                   net/http.serverHandler.ServeHTTP                                                                                                                                                     /opt/hostedtoolcache/go/1.17.7/x64/src/net/http/server.go:2879                                                                                                       net/http.(*conn).serve                                                                                                                                                               /opt/hostedtoolcache/go/1.17.7/x64/src/net/http/server.go:1930
这个应该怎么解决。或者说可以提供一个关于文件上传的demo吗，谢谢！

**Comment by criyle** [comment]
上传文件请使用 form data 然后提供 file 字段。比如上传 `input.txt` 是：

```
curl -v -F file=@input.txt localhost:5050/file
```

返回值是加了双引号的文件 id。
