### ISSUE TITLE
您好，我在执行测试时遇到了错误

### ISSUE THREAD

**Issue by AB259** [criyle/go-judge#33]
首先，感谢您提供的优质开源Code，下面是我的问题：
系统：CentOS 8.2 64位
安装方式：docker run -it --rm --privileged --shm-size=256m -p 5050:5050 criyle/executorserver
执行压力测试通过，使用压力测试的post也能accept
但使用postman测试示例中的单文件编译运行时出错，已安装g++
提交内容：
{
    "cmd": [{
        "args": ["/usr/bin/g++", "a.cc", "-o", "a"],
        "env": ["PATH=/usr/bin:/bin"],
        "files": [{
            "content": ""
        }, {
            "name": "stdout",
            "max": 10240
        }, {
            "name": "stderr",
            "max": 10240
        }],
        "cpuLimit": 10000000000,
        "memoryLimit": 104857600,
        "procLimit": 50,
        "copyIn": {
            "a.cc": {
                "content": "#include <iostream>\nusing namespace std;\nint main() {\nint a, b;\ncin >> a >> b;\ncout << a + b << endl;\n}"
            }
        },
        "copyOut": ["stdout", "stderr"],
        "copyOutCached": ["a.cc", "a"],
        "copyOutDir": "1"
    }]
}
返回结果：
[
    {
        "status": "Internal Error",
        "exitStatus": 0,
        "error": "execve: start: execve: no such file or directory",
        "time": 319510,
        "memory": 0,
        "runTime": 0,
        "files": {
            "stderr": "",
            "stdout": ""
        },
        "fileIds": {
            "a.cc": "C4IBYMMQ"
        },
        "fileError": [
            {
                "name": "a",
                "type": "CopyOutOpen",
                "message": "open a: no such file or directory"
            }
        ]
    }
]
使用file接口查询发现没有生成a文件，请问是什么原因或有什么解决方案，劳烦解答，感激不尽！

**Comment by criyle** [comment]
`execve: start: execve: no such file or directory` 指 `/usr/bin/g++` 文件不存在。可能是没有在容器内安装 `g++`。尝试 `docker ps` 找到沙箱服务对应容器，然后 `docker exec -it [容器名] /bin/bash` 然后执行 `apt update && apt install g++`。
