### ISSUE TITLE
2022/11/08 03:56:50 prefork environment failed  container: failed to start container fork/exec /proc/self/exe: invalid argument

### ISSUE THREAD

**Issue by yuluo-yx** [criyle/go-judge#44]
在执行
docker run -it --rm --privileged --shm-size=256m -p 5050:5050 criyle/executorserver
的过程中，我遇到了问题，已经执行了centos7的配置文件命令

下面是日志

[root@host-59-74-224-30 ~]# echo user.max_user_namespaces=10000 >> /etc/sysctl.d/98-userns.conf
[root@host-59-74-224-30 ~]# sysctl -p
net.ipv4.ip_forward = 1
[root@host-59-74-224-30 ~]# echo user.max_user_namespaces=10000 >> /etc/sysctl.d/98-userns.conf
[root@host-59-74-224-30 ~]# docker run -it --rm --privileged --shm-size=256m -p 5050:5050 criyle/executorserver
{"level":"info","ts":1667879810.046213,"caller":"executorserver/main.go:62","msg":"config loaded: &{ContainerInitPath: PreFork:1 TmpFsParam:size=128m,nr_inodes=4k NetShare:false MountConf:mount.yaml SeccompConf:seccomp.yaml Parallelism:16 CgroupPrefix:executor_server ContainerCredStart:0 SrcPrefix: Dir: TimeLimitCheckerInterval:100ms ExtraMemoryLimit:16.0 KiB OutputLimit:256.0 MiB CopyOutLimit:64.0 MiB OpenFileLimit:256 Cpuset: EnableCPURate:false CPUCfsPeriod:100ms FileTimeout:0s HTTPAddr::5050 EnableGRPC:false GRPCAddr::5051 MonitorAddr::5052 AuthToken: EnableDebug:false EnableMetrics:false Release:true Silent:false ForceGCTarget:20.0 MiB ForceGCInterval:5s Version:false}"}
{"level":"info","ts":1667879810.0463336,"caller":"executorserver/main.go:273","msg":"random seed: 2408806125596027837"}
{"level":"info","ts":1667879810.0476985,"caller":"env/env_linux.go:59","msg":"Created container mount at:Mounts: bind[/bin:bin:ro], bind[/lib:lib:ro], bind[/lib64:lib64:ro], bind[/usr:usr:ro], bind[/etc/ld.so.cache:etc/ld.so.cache:ro], bind[/etc/alternatives:etc/alternatives:ro], bind[/dev/null:dev/null:rw], bind[/dev/urandom:dev/urandom:rw], bind[/dev/random:dev/random:rw], bind[/dev/zero:dev/zero:rw], bind[/dev/full:dev/full:rw], tmpfs[w], tmpfs[tmp], proc[ro]"}
{"level":"info","ts":1667879810.0477355,"caller":"env/env_linux.go:76","msg":"Kernel version (3.10) < 4.6, don't unshare cgroup"}
{"level":"info","ts":1667879810.0477455,"caller":"env/env_linux.go:97","msg":"Creating container builder: hostName=executor_server, domainName=executor_server, workDir=/w"}
{"level":"info","ts":1667879810.0478673,"caller":"env/env_linux.go:129","msg":"Test created cgroup builder with: cgroup builder(v1): [cpuset, cpuacct, memory, pids]"}
{"level":"info","ts":1667879810.0675452,"caller":"executorserver/main.go:281","msg":"create 1 prefork containers"}
2022/11/08 03:56:50 prefork environment failed  container: failed to start container fork/exec /proc/self/exe: invalid argument

**Comment by criyle** [comment]
执行完 `echo user.max_user_namespaces=10000 >> /etc/sysctl.d/98-userns.conf` 需要重启生效

**Comment by yuluo-yx** [comment]
> 

好的，我试试

**Comment by riverstore** [comment]
Hi @criyle ,
I met the same issue on WSL2 (Ubuntu 22.04.2). I follow you guide but it doesn't work. Please help me.

Thanks a lot.
