### ISSUE TITLE
 "message": "open a: no such file or directory"

### ISSUE THREAD

**Issue by yuluo-yx** [criyle/go-judge#45]
在运行第一个示例（g++示例）的时候，需要创建或者上传额外的文件吗？

我请求的地址是：http://***********:5050/run

得到了这样的响应信息
[
    {
        "status": "Internal Error",
        "exitStatus": 0,
        "error": "execve: start: execve: no such file or directory",
        "time": 255185,
        "memory": 0,
        "runTime": 0,
        "files": {
            "stderr": "",
            "stdout": ""
        },
        "fileIds": {
            "a.cc": "3TIW2DYO"
        },
        "fileError": [
            {
                "name": "a",
                "type": "CopyOutOpen",
                "message": "open a: no such file or directory"
            }
        ]
    }
]

**Comment by criyle** [comment]
需要在容器中安装 g++ ，比方说 `docker attach ...` 之后 `apt install g++`

**Comment by yuluo-yx** [comment]
> 需要在容器中安装 g++ ，比方说 `docker attach ...` 之后 `apt install g++`

谢谢您的耐心回答，我以为是要在宿主机中安装g++。
