### ISSUE TITLE
沙箱网络问题

### ISSUE THREAD

**Issue by qq670176019** [criyle/go-judge#46]
1、你好，请问下沙箱中能有访问外部网络的开关或者配置吗？我们现在有一个评测场景，通过Python使用pandas读取表格，然后利用评测机验证获取到的数组的值进行正确性验证，而pands读取到的表格在外网上，需要使用pandas的read_excel函数获取，但是现在使用评测机时会报URLError错误，因此想问下能否有办法打开沙盒的外网访问权限。

2、另外想问一下，能否放一下Python评测的示例，现在文档中有c++的示例代码，python的没有，恕我愚钝，没有参透，一直用着go-judge-demo的/api/submit去提交评测，现在想把评测的CPU和内存限制个性化设置，如您能发几个Python的示例，万分感谢！

**Comment by criyle** [comment]
1. 可以使用 `-net-share` 来共享本机网络，但是请注意并不建议在生产环境中使用。用户可以提交代码来连接网络环境中其他设备。建议使用 copyIn 来复制到沙箱容器当中本机读写
2. 比如
```
{
	"cmd": [{
		"args": ["python3", "1.py"],
		"env": ["PATH=/usr/bin:/bin"],
		"files": [{
			"content": ""
		}, {
			"name": "stdout",
			"max": 10240
		}, {
			"name": "stderr",
			"max": 10240
		}],
		"cpuLimit": 1000000000,
                "realCpuLimit": 2000000000,
		"memoryLimit": 104857600,
		"procLimit": 50,
		"copyIn": {
			"1.py": {
				"content": "with open('2.txt') as f:\n    print(f.read())"
			},
                       "2.txt": {
                                "content": "content"
                       }
		}
	}]
}
```

**Comment by qq670176019** [comment]
> 

非常感谢大佬不厌其烦回复问题，感激不尽！我马上尝试一下
