### ISSUE TITLE
运行Python的matplotlib库问题

### ISSUE THREAD

**Issue by qq670176019** [criyle/go-judge#47]
你好作者，我在沙盒中运行matplotlib时，遇到了如下问题：
# 一、待评测代码
`
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data1 = pd.read_csv(r'https://dp.xinchanjiao.com/data/test1.csv')   
data2 = pd.read_csv(r'https://dp.xinchanjiao.com/data/test2.csv')   
data3 = data1.merge(data2,on='地区',how='left')
print('合并后数据行列数分别为:{}行,{}列。'.format(data3.shape[0],data3.shape[1]))
data3.head(5)#查看合并后数据的前5行
nan_num = data3.isna().sum().sum()

row_duplicated = data3.duplicated().sum()
print(f'重复行总数为:{row_duplicated}')
barh_data = barh_data = data3.groupby('省/自治区').agg({'利润':'sum','销售额':'sum'}).sort_values('利润',ascending=True)
barh_data.head()#查看数据前5行
barh = barh_data.plot(kind='barh',figsize=(16,12),width=0.8)
plt.title('各省市销售额&利润条形图',fontdict={'fontsize':20})
plt.xlabel('金额(元)')
plt.ylabel('省/自治区')
plt.grid()
plt.legend()
plt.show()
tem_data = pd.pivot_table(data=data3,values=['销售额'],index=['地区经理'],columns=['类别'],aggfunc='sum')#使用透视函数筛选数据
tem_data.head()#查看数据前5行
for i in range(tem_data.shape[0]):
    tem_data.iloc[i].plot(marker='o',ls='--',figsize=(16,7))
plt.title('地区经理&商品类别销售额折线图',fontsize=20)
plt.xlabel('类别')
plt.ylabel('金额(元)')
plt.legend()
plt.grid()
plt.show()
data4 = data3[(data3['销售额']>1000) & (data3['利润']<0)]
`
# 二、发送给评测机的JSON
`
{"cmd":[{"args":["/usr/bin/python3","1.py"],"cpuLimit":1000000000,"files":[{"content":""},{"max":9999999,"name":"stdout"},{"max":9999999,"name":"stderr"}],"realCpuLimit":2000000000,"memoryLimit":104857600,"copyIn":{"1.py":{"content":"import numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\ndata1 = pd.read_csv(r'0.csv')   \ndata2 = pd.read_csv(r'1.csv')   \ndata3 = data1.merge(data2,on='地区',how='left')\ndata3.head(5)#查看合并后数据的前5行\nnan_num = data3.isna().sum().sum()\nrow_duplicated = data3.duplicated().sum()\nbarh_data = barh_data = data3.groupby('省/自治区').agg({'利润':'sum','销售额':'sum'}).sort_values('利润',ascending=True)\nbarh_data.head()#查看数据前5行\nbarh = barh_data.plot(kind='barh',figsize=(16,12),width=0.8)\nplt.title('各省市销售额&利润条形图',fontdict={'fontsize':20})\nplt.xlabel('金额(元)')\nplt.ylabel('省/自治区')\nplt.grid()\nplt.legend()\nplt.show()\ntem_data = pd.pivot_table(data=data3,values=['销售额'],index=['地区经理'],columns=['类别'],aggfunc='sum')#使用透视函数筛选数据\ntem_data.head()#查看数据前5行\nfor i in range(tem_data.shape[0]):\n    tem_data.iloc[i].plot(marker='o',ls='--',figsize=(16,7))\nplt.title('地区经理&商品类别销售额折线图',fontsize=20)\nplt.xlabel('类别')\nplt.ylabel('金额(元)')\nplt.legend()\nplt.grid()\nplt.show()\ndata4 = data3[(data3['销售额']>1000) & (data3['利润']<0)]\n\nprint(data1.shape[0])"},"1.csv":{"content":"﻿
#############################内容太长，超出了输入框限制，具体内容在1.py中涉及到的csv文件中################
"}},"env":["PATH=/usr/bin:/bin"],"procLimit":50}]}
`

# 三、评测机返回的JSON
`
[{"status":"Nonzero Exit Status","exitStatus":1,"time":773798045,"memory":47820800,"runTime":458349828,"files":{"stderr":"Traceback (most recent call last):\n  File \"/w/1.py\", line 3, in \u003cmodule\u003e\n    import matplotlib.pyplot as plt\n  File \"/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py\", line 892, in \u003cmodule\u003e\n    dict.update(rcParams, _rc_params_in_file(matplotlib_fname()))\n  File \"/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py\", line 569, in matplotlib_fname\n    for fname in gen_candidates():\n  File \"/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py\", line 566, in gen_candidates\n    yield os.path.join(get_configdir(), 'matplotlibrc')\n  File \"/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py\", line 275, in wrapper\n    ret = func(**kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py\", line 512, in get_configdir\n    return _get_config_or_cache_dir(_get_xdg_config_dir)\n  File \"/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py\", line 471, in _get_config_or_cache_dir\n    configdir = Path(xdg_base_getter(), \"matplotlib\")\n  File \"/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py\", line 452, in _get_xdg_config_dir\n    return os.environ.get('XDG_CONFIG_HOME') or str(Path.home() / \".config\")\n  File \"/usr/lib/python3.10/pathlib.py\", line 998, in home\n    return cls(\"~\").expanduser()\n  File \"/usr/lib/python3.10/pathlib.py\", line 1438, in expanduser\n    raise RuntimeError(\"Could not determine home directory.\")\nRuntimeError: Could not determine home directory.\n","stdout":""}}]
`

# 四、问题分析和尝试
感觉是matplotlib问题，根据提示，百度了一下，配置过如下：
`
import os
os.environ['MPLCONFIGDIR'] = os.getcwd() + "/configs/"
`
结果返回的是：
`
[{"status":"Time Limit Exceeded","exitStatus":9,"time":1100516463,"memory":57921536,"runTime":1004221715,"files":{"stderr":"Fontconfig error: Cannot load default config file\n","stdout":""}}]
`

请问作者及各位使用该沙盒的朋友有没有遇到这种问题，是怎么解决的呢？

**Comment by criyle** [comment]
可以尝试添加 `HOME=/w` 到 env 环境变量中
