### ISSUE TITLE
/run接口支持非阻塞吗？

### ISSUE THREAD

**Issue by winterant** [criyle/go-judge#48]
/run接口支持非阻塞吗？比如有个任务需要允许很长时间，服务端并不需要等待它执行结束，而是立即返回。而运行结果，可以在服务端开一个接口在后台监听，或者开一个轮询进程查询结果。请问一下，现在能实现这种方式吗？

**Comment by criyle** [comment]
可以使用 WebSocket 连接 `/ws` 接口，请求是异步的。参数和 `/run` 一样不过需要加 `requestId` 为 key 来区分不同请求。
