### ISSUE TITLE
启动的时候出现这个问题，没有对源代码进行修改

### ISSUE THREAD

**Issue by DaZuiZui** [criyle/go-judge#55]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/66861267/218999307-37d808d3-7b1c-4642-8750-eafa71287987.png">

**Comment by criyle** [comment]
以非root用户启动时不启用 cgroup 资源限制而使用传统的rlimit限制。只是一个warn级别日志告知这个特性。
