### ISSUE TITLE
拿不到返回JSON

### ISSUE THREAD

**Issue by Hnitrogen** [criyle/go-judge#58]
我使用命令行gojudge，开启了grpc，在前端成功向/run post了一段代码，可以在/file下查看到，但是我前端拿不到他的返回Json，前端报错是跨域问题。

**Comment by criyle** [comment]
go-judge 作为沙箱服务是提供给后端调用而不是直接从前端访问。接口并没有做鉴权，限流，参数校验，如果直接暴露有拒绝服务风险。如果执意需要从前端直接访问，请用反向代理（例如nginx）加上跨域请求头。

可以参考 demo (goj.ac) 的实现：https://github.com/criyle/go-judger-demo

**Comment by Hnitrogen** [comment]
懂了，谢谢大佬🙏
