### ISSUE TITLE
Contact method

### ISSUE THREAD

**Issue by AlphaNecron** [criyle/go-judge#59]
Do you have Discord? I'm planning to make a online judge platform and need some help with go-sandbox, can you give me your Discord? Thanks in advance.

**Comment by criyle** [comment]
Hello AlphaNecron, if you need any help, you can reach out via [discussion](https://github.com/criyle/go-judge/discussions) for this repo and I'll answer them when I am awake.

**Comment by AlphaNecron** [comment]
How do I generate a seccomp config for my C++ program? strace does not seem to work, modifying your cmd/runprog code btw.

**Comment by criyle** [comment]
You may use `./runprog -show-trace-details ./your_program` to find out which syscall got blocked and you can add it to the config at `cmd/runprog/config` accordingly.

**Comment by AlphaNecron** [comment]
Added that but it does not work lol.

**Comment by AlphaNecron** [comment]
Can you give me your Discord, you seem to be inactive on GitHub though.
