### ISSUE TITLE
更改cmd的files中的成员顺序后，返回结果异常。

### ISSUE THREAD

**Issue by LQQ4321** [criyle/go-judge#63]
正常情况：

![image](https://user-images.githubusercontent.com/87405212/234288686-85ab89e5-b0e8-48a0-8782-1cfb7dcd17f4.png)
![image](https://user-images.githubusercontent.com/87405212/234288757-55f887bb-859d-4939-b970-40befe3d796d.png)

异常情况：

![image](https://user-images.githubusercontent.com/87405212/234288181-4bf15b6d-ad18-42e3-a3b8-2bcd8b678efe.png)
![image](https://user-images.githubusercontent.com/87405212/234288512-3583d8a7-65b2-4e55-97f7-4271d785c209.png)

建议作者在README.md中说明一下这里。

**Comment by criyle** [comment]
files 是有序列表，下标是文件描述符，调换顺序会改变运行时文件描述符。使用者应当知晓 0 为标准输入， 1 为标准输出，2 为标准错误。

Ref: https://www.man7.org/linux/man-pages/man3/stdin.3.html
