### ISSUE TITLE
默认不开启seccomp，安全性能够得到保证吗？

### ISSUE THREAD

**Issue by zhouyusd** [criyle/go-judge#65]

**Comment by criyle** [comment]
默认的情况下，程序以 无任何[特权](https://man7.org/linux/man-pages/man7/capabilities.7.html) ，禁止权限提升 PR_SET_NO_NEW_PRIVS ，在隔绝网络和限制文件系统访问的命名空间中，被 cgroup 限制资源使用运行。安全性由 Linux 容器技术保证。

由于 seccomp 由于和运行架构，内核版本和编译器耦合，默认不开启，可自行调配开启以增加安全性。

如果有测试安全性的想法，欢迎来 [测试站](https://goj.ac) 提交测试。

**Comment by zhouyusd** [comment]
thx
