### ISSUE TITLE
在windows中使用copyOutDir将文件转存时，文件为空（文件大小为0KB）

### ISSUE THREAD

**Issue by Source-Roc** [criyle/go-judge#74]
我在window上运行测试环境，在cmd中启动沙盒，启动参数参数为`executorserver_1.6.8_windows_amd64.exe -dir ./test`  
由于`copyOutDir`使用相对定位转存文件，同时在windows中的临时目录不容易定位，所以使用了-dir 设置为本地缓存（也测试不使用-dir 参数启动，但转存的文件同样是空（文件大小为0KB））  
为了避免可能是因为windows权限的问题，在使用-dir ./test 测试时，已经提前将test文件夹的权限设置为了任何用户都可以读写  
也测试过以管理员方式启动cmd，然后启动沙盒，但是发现同样转存的文件为空（文件大小为0KB）

下面提交的参数
``` json
{
    "cmd": [
        {
            "args": [
                "D:/JudgeEnvs/Cpp/mingw64/bin/g++",
                "-std=c++14",
                "main.cpp",
                "-o",
                "main.exe"
            ],
            "env": [
                "LANG=en_US.UTF-8",
                "LC_ALL=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "PATH=D:/JudgeEnvs/Cpp/mingw64/bin"
            ],
            "files": [
                {
                    "content": ""
                },
                {
                    "name": "stdout",
                    "max": 33554432
                },
                {
                    "name": "stderr",
                    "max": 33554432
                }
            ],
            "cpuLimit": 10000000000,
            "clockLimit": 10000000000,
            "memoryLimit": 536870912,
            "procLimit": 128,
            "stackLimit": 268435456,
            "copyIn": {
                "main.cpp": {
                    "content": "#include<iostream>\nusing namespace std;\n\nint main() {\n    string s;\n    cin>>s;\n    cout<<s<<endl;\n    \n    return 0;\n}"
                }
            },
            "copyOut": [
                "stdout",
                "stderr"
            ],
            "copyOutCached": [
            ],
            "copyOutDir": "123456"
        }
    ]
}

```

返回的参数
``` json
[
    {
        "status": "Accepted",
        "exitStatus": 0,
        "time": 359375000,
        "memory": 53260288,
        "runTime": 0,
        "files": {
            "stderr": "",
            "stdout": ""
        }
    }
]

```

**Comment by criyle** [comment]
抱歉暂时没有 windows 环境用于测试。当 `copyOutCached` 参数里面指定 `main.exe` 在 `-dir` 目录中会有以 `fileId` 命名的文件吗。测试时 windows 版本是多少

**Comment by Source-Roc** [comment]
> 抱歉暂时没有 windows 环境用于测试。当 `copyOutCached` 参数里面指定 `main.exe` 在 `-dir` 目录中会有以 `fileId` 命名的文件吗。测试时 windows 版本是多少

测试的版本是`1.6.8  executorserver_1.6.8_windows_amd64`，
当使用copyOutCached:['main.exe'] 时是有以fileId命名的文件的，同时修改后缀之后文件是可以正常使用的，但是copyOutDir内的文件是空的

**Comment by Source-Roc** [comment]
我通过克隆源码在本地运行，可能发现问题的所在

go版本`1.20.7`
环境`Windows 10 家庭中文版 22H2`
运行IED`GoLand 2021.3.4`
涉及到的文件`envexec/file_util_others.go - 62行`和`envexec/file_util_others.go - 69行`
提交版本`9e403cb2d2e63d90f1a969c43b1c8eb725ad46cc`

两处代码注释中都标明是`check regular file`，但是在`file_util_others.go`文件中使用的与`&`操作，在`file_util_others.go`文件中使用的是或`|`操作，两者相同功能，但代码却相反。
_猜测正常情况下`stat.Mode()`的返回值不为零，所以`stat.Mode()|os.ModeType != 0`恒成立，导致无法进行下一步文件的复制操作，所以在windows下使用`copyOutDir`功能无效_
我尝试将`file_util_others.go`文件中的或`|`操作修改为与`&`操作，文件复制成功

由于我正在初学go语言，对于部分方法和参数的具体功能不了解，所以将发现提交并在这里向您询问一下具体的原因
@criyle

**Comment by criyle** [comment]
好像是修 linux 的忘记 windows 的了 [commit](https://github.com/criyle/go-judge/commit/0db852c2421776a9cde6a9f8986a64b5d2adc7c6)。您可以提交一个 PR 或者我可以在下个版本改正。最近没有 windows 环境不能测试，请见谅。

**Comment by Source-Roc** [comment]
好的，已修改并提交PR
