### ISSUE TITLE
请问如何用/run restful接口来编译和运行java代码

### ISSUE THREAD

**Issue by mc23101** [criyle/go-judge#75]
请问如何用/run restful接口来编译和运行java代码

**Comment by criyle** [comment]
看 goj.ac 上的演示和 #26

**Comment by mc23101** [comment]
> 看 goj.ac 上的演示和 #26

那个我go语言的代码看不懂

**Comment by criyle** [comment]
您可以在下拉框里面选择java来查看编译和运行时使用的命令行参数。替换这些到g++例子里面即可使用。

**Comment by mc23101** [comment]
我在docker容器控制台里面可以用javac编译java，用post请求无法编译，报错
`Exception in thread "main" java.lang.InternalError: Error loading java.security file java.base/java.security.Security.initialize(Security.java:106) java.base/java.security.Security$1.run(Security.java:84) java.base/java.security.Security$1.run(Security.java:82) java.base/java.security.AccessController.doPrivileged(AccessController.java:318) java.base/java.security.Security.<clinit>(Security.java:82) java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57) java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48) java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72) java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36) java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:45) java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:269) java.base/java.security.AccessController.createWrapper(AccessController.java:647) java.base/java.security.AccessController.doPrivileged(AccessController.java:460) java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(ResourceBundle.java:3614) java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1837) java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1768) java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722) java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722) java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656) java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1575) java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549) java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932) jdk.compiler/com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:121) jdk.compiler/com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:140) jdk.compiler/com.sun.tools.javac.util.JavacMessages.setCurrentLocale(JavacMessages.java:80) jdk.compiler/com.sun.tools.javac.util.JavacMessages.<init>(JavacMessages.java:112) jdk.compiler/com.sun.tools.javac.util.JavacMessages.<init>(JavacMessages.java:89) jdk.compiler/com.sun.tools.javac.util.JavacMessages.instance(JavacMessages.java:58) jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.<init>(JCDiagnostic.java:71) jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.instance(JCDiagnostic.java:61) jdk.compiler/com.sun.tools.javac.util.Log.<init>(Log.java:319) jdk.compiler/com.sun.tools.javac.util.Log.<init>(Log.java:256) jdk.compiler/com.sun.tools.javac.util.Log.instance(Log.java:236) jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:203) jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176) jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64) jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)`

**Comment by criyle** [comment]
你的 java 版本多少，是如何安装的

**Comment by mc23101** [comment]
版本是Openjdk-17-jdk  使用apt install openjdk-17-jdk安装的

**Comment by mc23101** [comment]
这个是我的请求body
`{
    "cmd": [{
        "args": ["/usr/bin/javac","-source","8", "Main.java"],
        "env": ["PATH=/usr/bin"],
        "files": [{
            "content": ""
        }, {
            "name": "stdout",
            "max": 10240
        }, {
            "name": "stderr",
            "max": 10240
        }],
        "cpuLimit": 10000000000,
        "memoryLimit": 104857600,
        "procLimit": 50,
        "copyIn": {
            "Main.java": {
                "content": "public class Main {\npublic static void main(String[] args) {\n System.out.println('aaa');\n }\n}"
            }
        },
        "copyOut": ["stdout", "stderr"],
        "copyOutCached": []
    }]
}`

**Comment by criyle** [comment]
openjdk17 似乎需要一些特别的配置

进入容器，打开 `/opt/mount.yaml`，在 `target: /.env` 行后加入

```yaml
  - type: bind
    source: /etc/java-17-openjdk
    target: /etc/java-17-openjdk
``` 

保存后重启容器

**Comment by mc23101** [comment]
好的谢谢大佬，可以成功运行啦

**Comment by lm-lan** [comment]
感谢大佬，启动时新增mount.yaml，解决了
