### ISSUE TITLE
[Feature Request] 在 config 中提供当前 sandbox 使用的内存使用量计数指标

### ISSUE THREAD

**Issue by pandadtdyy** [criyle/go-judge#80]
如文档所说，沙盒中会使用 `memory.max_usage_in_bytes` / `maxrss` / `memory.peak` 三种指标对内存使用量计数，可否在 config
中提供目前正在使用的指标？

**Comment by criyle** [comment]
- `memory.max_usage_in_bytes` cgroup v1 
-  `max_rss` 非 root 或者 cgroup v2 以及 linux 内核版本 < 5.19
-  `memory.peak` cgroup v2 并且 linux 内核版本 >= 5.19
config 中提供了当前使用的 cgroup 版本，也许可以作为参考

**Comment by pandadtdyy** [comment]
`memory.peak` 和 `memory.max_usage_in_bytes` 哪个的精准度更高呢？ 在考虑是否提示用户可以换到 cgroup v1

**Comment by criyle** [comment]
抱歉，目前并没有测试 5.19 内核的环境，`memory.peak` 来自社区的贡献。待我实测之后再做进一步的回答。

**Comment by criyle** [comment]
在 `arm64` 平台 `ubuntu server 23.04 (linux kernel 6.2)` 中实测 `cgroup v2` 提供的 `memory.peak` 计量和 `cgroup v1` 提供的 `memory.max_usage_in_bytes` 相当。鉴于 5.19 为较新内核，可以推荐小于此版本的用户切换至 `cgroup v1` 来获取精确测量，而对于更新版本用户可以看个人喜好。

**Comment by pandadtdyy** [comment]
Thanks!
