### ISSUE TITLE
如何在沙盒里面编译和运行Java代码

### ISSUE THREAD

**Issue by pllydong** [criyle/go-judge#82]
我查了好多文档也没看到有提到这件事，但是好像大家都会啊，是我那里漏了什么嘛？我是通过docker来运行沙盒，我进入沙盒容器内部也没有找到java环境吗？是需要自己在容器内部安装java环境吗？

**Comment by criyle** [comment]
是的，容器仅为标准 `debian` 容器，并没有编译器。可以进入容器使用 `apt` 安装 `openjdk` 来编译运行 `java`。或者可以构建一个含有编译器的镜像 [参考](https://github.com/criyle/go-judger-demo/blob/master/Dockerfile.exec)。

**Comment by pllydong** [comment]
太感谢了
