### ISSUE TITLE
沙箱长时间运行之后会无法使用

### ISSUE THREAD

**Issue by Cishoon** [criyle/go-judge#84]
汇报如下错误： filed to create container file open C:\Users\xx\AppData\Local\Temp\2\es2136709772/stdout: Access is denied.
重启之后又能恢复正常

**Comment by criyle** [comment]
在 windows 11 arm 环境中测试无法复现，请提供详细的复现步骤和测试环境

**Comment by Cishoon** [comment]
启动命令：go-judge.exe -dir ./gojudge_temp -file-timeout 1h
在Windows10 arm环境中持续运行1天以上，之后使用Postman或其他工具发送任意 /run 请求，返回报错信息 filed to create container file open C:\Users\xx\AppData\Local\Temp\2\es2136709772/stdout: Access is denied.

**Comment by criyle** [comment]
确实没有在长达一天的维度上进行测试。有可能是临时文件夹被清理之类的原因导致的。不过既然使用 windows 10，更加建议使用 linux 版本在 wsl2 中运行。毕竟 windows 版的沙箱安全性基本等同于 chrome 网页进程，也有可能逃逸的方法，因此不建议在生产环境中使用。

**Comment by criyle** [comment]
无法复现，可能与系统中存在的第三方软件有关。如果能提供更详细的复现步骤，欢迎重开 issue 。
