### ISSUE TITLE
遇到个问题 不知道如何解决啊 输入sudo docker run -it --rm --privileged --shm-size=256m -p 5050:5050 criyle/executorserver

### ISSUE THREAD

**Issue by content-finaly** [criyle/go-judge#90]
sudo docker run -it --rm --privileged --shm-size=256m -p 5050:5050 criyle/executorserver
{"level":"info","ts":1699204744.1748333,"caller":"executorserver/main.go:61","msg":"config loaded: &{ContainerInitPath: PreFork:1 TmpFsParam:size=128m,nr_inodes=4k NetShare:false MountConf:mount.yaml SeccompConf:seccomp.yaml Parallelism:1 CgroupPrefix:executor_server ContainerCredStart:0 SrcPrefix:[] Dir: TimeLimitCheckerInterval:100ms ExtraMemoryLimit:16.0 KiB OutputLimit:256.0 MiB CopyOutLimit:256.0 MiB OpenFileLimit:256 Cpuset: EnableCPURate:false CPUCfsPeriod:100ms FileTimeout:0s HTTPAddr::5050 EnableGRPC:false GRPCAddr::5051 MonitorAddr::5052 AuthToken: EnableDebug:false EnableMetrics:false Release:true Silent:false ForceGCTarget:20.0 MiB ForceGCInterval:5s Version:false}"}
{"level":"info","ts":1699204744.174918,"caller":"executorserver/main.go:282","msg":"random seed: -4349787481769717344"}
{"level":"info","ts":1699204744.175992,"caller":"env/env_linux.go:59","msg":"Created container mount at:Mounts: bind[/bin:bin:ro], bind[/lib:lib:ro], bind[/lib64:lib64:ro], bind[/usr:usr:ro], bind[/etc/ld.so.cache:etc/ld.so.cache:ro], bind[/etc/alternatives:etc/alternatives:ro], bind[/dev/null:dev/null:rw], bind[/dev/urandom:dev/urandom:rw], bind[/dev/random:dev/random:rw], bind[/dev/zero:dev/zero:rw], bind[/dev/full:dev/full:rw], tmpfs[w], tmpfs[tmp], proc[ro]"}
{"level":"info","ts":1699204744.1760283,"caller":"env/env_linux.go:76","msg":"Kernel version (3.10) < 4.6, don't unshare cgroup"}
{"level":"info","ts":1699204744.176044,"caller":"env/env_linux.go:97","msg":"Creating container builder: hostName=executor_server, domainName=executor_server, workDir=/w"}
{"level":"info","ts":1699204744.1764011,"caller":"env/env_linux.go:129","msg":"Test created cgroup builder with: cgroup builder(v1): [cpuset, cpuacct, memory, pids]"}
{"level":"info","ts":1699204744.1801128,"caller":"executorserver/main.go:290","msg":"create 1 prefork containers"}
2023/11/05 17:19:04 prefork environment failed  container: failed to start container fork/exec /proc/self/exe: invalid argument

**Comment by criyle** [comment]
CentOS 7?

**Comment by content-finaly** [comment]
是的c7， 昨天我虚拟机试了一下 2+2的 128m可以运行  正式服务器128m   64m都不可以运行

**Comment by criyle** [comment]
centOS 7需要开启 user namespace 支持，可以看 readme 里面对应的部分
