### ISSUE TITLE
同一份代码，测评时限浮动较大，有什么好的解决方案吗？

### ISSUE THREAD

**Issue by hkerym** [criyle/go-judge#91]
服务器配置：
* 阿里云算力型服务器4核8G。
* Ubuntu 22.04

服务器运行内容：
* docker运行，容器里面包含一个判题机.jar以及一个go-judge沙箱。

并行测评2份代码，时限还算稳定，但是并行测评3份、4份，时限浮动较大。

请问有什么好的解决方案嘛？

**Comment by criyle** [comment]
4核仅对应2物理核心，在cpu使用率无限制的情况下会争抢运行时间。可以考虑使用 `cpuRateLimit:1000`限制仅使用单核来降低资源争抢。或者也可以考虑`cpuSetLimit`手动绑定核心

**Comment by hkerym** [comment]
感谢解答
